"""add indexes for foreign keys

Revision ID: 77e84ee38830
Revises: a0878f5b2797
Create Date: 2026-07-22 15:58:13.162576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e84ee38830'
down_revision: Union[str, Sequence[str], None] = 'a0878f5b2797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_projects_owner_id', 'projects', ['owner_id'], unique=False)
    op.create_index('ix_tasks_project_id', 'tasks', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_project_id', table_name='tasks')
    op.drop_index('ix_projects_owner_id', table_name='projects')
    # ### end Alembic commands ###
